# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    trip.data_renderer:
        class: TriplogBundle\Service\TripDataRenderer
        arguments: ['@doctrine.orm.entity_manager', '@router']

    trip.login_form_authenticator:
        class: TriplogBundle\Security\LoginFormAuthenticator
        autowire: true

    trip.doctrine.hash_password_listener:
        class: TriplogBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    trip.file_uploader:
        class: TriplogBundle\Service\FileUploader
        arguments: ['%image_directory%']

